### ISSUE TITLE
Stop does not work

### ISSUE THREAD

**Issue by quozl** [zhirzh/sugarizer-activity-moon#12]
Stop button does not work in Sugar 0.110 on Ubuntu 16.04 using the `sugar-activity-web` wrapper.  There is no response to clicking the button.

Tested 88413e8ee8799cf3324e3675f525d46e86a0449d

For comparison, if it helps, the [Gears Activity](https://github.com/tchx84/gears-activity) does stop.

**Comment by zhirzh** [comment]
This is the Sugarizer activity Moon - web port of Sugar activity Moon.

The stop button in the final release code works: http://try.sugarizer.org/activities/Moon.activity/

However, since the button is tied to Sugarizer platform, it will not work in the standalone demo: https://zhirzh.github.io/sugarizer-activity-moon/

**Comment by icarito** [comment]
This actually is an issue with the sugar-web library as propose by Sugarizer - thus a bug with moon-activity, not Sugar. I don't think @zhirzh you understood the issue, it's with Sugar learning platform.

**Comment by quozl** [comment]
Is fixed by https://github.com/zhirzh/sugarizer-activity-moon/pull/13
